### ISSUE TITLE
Some questions about your dataset. 

### ISSUE THREAD

**Issue by Moqixis** [GewelsJI/VPS#10]
Hi, sorry to bother you. I have some questions about your dataset, and I have tried to contact the author of the SUN dataset but got no response. So I still take the liberty to ask you. 

It is mentioned in your document(https://github.com/GewelsJI/VPS/blob/main/docs/DATA_DESCRIPTION.md): 
_As such, it yields the final version of our SUN-SEG dataset, which includes 49,136 polyp frames (i.e., positive part) and 109,554 non-polyp frames (i.e., negative part) taken from different 285 and 728 colonoscopy videos clips, as well as the corresponding annotations. The following sections will provide details about our SUN-SEG point-by-point._

Are there only frames containing polyps in your videos in the positive part? And how do you use the non-polyp frames in your train 
 and test dataset? How do you deal with the non-polyp frames when you calculate evaluation such as Dice and so on?

Thank you very much and look forward to your reply.

**Comment by GewelsJI** [comment]
Q1. Are there only frames containing polyps in your videos in the positive part? And how do you use the non-polyp frames in your train and test dataset?
A1. In our journal version, we only consider the situation of assuming at least a polyp exists in a frame. So we do not include negative sample in our training pipeline. We plan to use both of them in the near future.

Q2. How do you deal with the non-polyp frames when you calculate evaluation such as Dice and so on?
Q2. Nice question. To my best known, existing metrics can not well evaluate the real performance for those non-polyp frames.

**Comment by Moqixis** [comment]
> Hi, @Moqixis
> 
> Q1. Are there only frames containing polyps in your videos in the positive part? And how do you use the non-polyp frames in your train and test dataset? A1. In our journal version, we only consider the situation of assuming at least a polyp exists in a frame. So we do not include negative sample in our training pipeline. We plan to use both of them in the near future.
> 
> Q2. How do you deal with the non-polyp frames when you calculate evaluation such as Dice and so on? A2. Nice question. To my best known, existing metrics can not well evaluate the real performance for those non-polyp frames.

I understand. Thank you very much for your reply!!!
