### ISSUE TITLE
Data loading problem

### ISSUE THREAD

**Issue by zzgzzgz** [GewelsJI/VPS#12]
Hello, the data set format is formatted according to the requirements, but this error occurs

File "./lib/dataloader/dataloader.py", line 32, in <lambda>
    int(name.split('-')[0].split('_')[-1]),
ValueError: invalid literal for int() with base 10: '00003.jpg'

I'm not sure what that is

**Comment by johnson111788** [comment]
Hi,

Could you provide the value of the variable "tmp_list" in your training process?

Thanks,
Johnson

**Comment by GewelsJI** [comment]
Hi, @johnson111788 @zzgzzgz 

This issue has not received any further response and I just closed this. If @zzgzzgz needs any helps, please re-open this page, thanks.

Best,
Ge-Peng
