### ISSUE TITLE
Some errors when creating the environment

### ISSUE THREAD

**Issue by XinZhenRen** [GewelsJI/VPS#13]
Hi, your work is respectable！But I have some problems. Could you please help me?
when i type
`pip install git+https://github.com/pytorch/tnt.git@master`
there are some errors occured.
![image](https://user-images.githubusercontent.com/71360303/230569136-6ed9e86f-23ba-40db-afb8-44debfe745be.png)

By the way, when I run `python setup.py build develop`, I also have some problmes.

![image](https://user-images.githubusercontent.com/71360303/230569834-93360365-abba-4f56-9d5a-84e6a3b4c33b.png)

**Comment by GewelsJI** [comment]
You can try `pip install torchtnt`

**Comment by GewelsJI** [comment]
Hi, @XinZhenRen 

I would like to close this issue since I have not received any response from you. If you have any further questions, please feel free to reopen this page.
