### ISSUE TITLE
I referred to the solution to #3, but it seems different from my error report

### ISSUE THREAD

**Issue by yike5022** [GewelsJI/VPS#15]
"python setup.py build develop"instructions can run,  "self_cuda_backend"cannot be imported in PNSPlusModule.py, PNSPlusNetwork.py also cannot be Compiled

**Comment by GewelsJI** [comment]
Hi, please ensure that you have a consistent environment as our provided. Also, could you please provide more hardware and software (like cuda etc.) information here?

**Comment by yike5022** [comment]
cuda11.7, and PNSPlusNetwork.py can be compiled now, train.py cannot run

**Comment by GewelsJI** [comment]
Sorry, I have not tested our code on cuda11.7. But, kindly follow the instructions provided in #3, I think there would be not too many modifications on the current code. Or you can change your cuda version, this would be the simplest way to solve it.
