### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by yhuis** [GewelsJI/VPS#16]
为什么运行python setup.py build develop会出现语法报错？？？我并没有更改它，而是直接从github下载得到的。
![2](https://github.com/GewelsJI/VPS/assets/137278967/2c0f6d15-bd9c-41ac-b2f7-15d9243b9ace)

**Comment by GewelsJI** [comment]
你好，建议在linux系统去编译这个op算子，windows下面会出现很多不适配的问题，改动成本可能比较大！

**Comment by yhuis** [comment]
你好，使用linux系统会报no file错误
![3](https://github.com/GewelsJI/VPS/assets/137278967/14dd33f5-fd11-4beb-9ce4-592ea1d8322a)

**Comment by GewelsJI** [comment]
Transfer to https://github.com/GewelsJI/VPS/issues/17
