### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by yhuis** [GewelsJI/VPS#17]
你好，使用linux编译会报错怎么解决？
![4](https://github.com/GewelsJI/VPS/assets/137278967/646c1990-5280-4409-82c7-985ac08e590f)

**Comment by GewelsJI** [comment]
看样子是编译op算子出现的问题，不过很难根据这个报错得到具体的解决方案，能够提供一下详细的操作流程最好，最好提前确保cuda驱动和pytorch版本能够对应
