### ISSUE TITLE
Request for Access to SUN Colonoscopy Video Database

### ISSUE THREAD

**Issue by wade0604** [GewelsJI/VPS#19]
Thank you very much for making this dataset available. We sent our application email to [hitoh@mori.m.is.nagoya-u.ac.jp](mailto:hitoh@mori.m.is.nagoya-u.ac.jp), but it was returned. Therefore, we would like to confirm if the email address for submitting applications is correct.

**Comment by GewelsJI** [comment]
Please send your request to my email: gepengai.ji@gmail.com
