### ISSUE TITLE
About this, how can I use it？

### ISSUE THREAD

**Issue by Zachary-Hwang** [GewelsJI/VPS#20]
I downloaded the benchmark file, but I don't know how I should use it. Could you please tell me? Thanks!
“We provide an out-of-the-box evaluation toolbox for the VPS task, which is written in Python style. You can just run it to generate the evaluation results on your custom approach. Or you can directly download the complete VPS benchmark including prediction map of each competitor at download link: [OneDrive](https://anu365-my.sharepoint.com/:u:/g/personal/u7248002_anu_edu_au/ESS2WHOQvLhMl5ci8wNO6yYBjnh6EVcp5vYO1z4JoOKUNg?e=nJe6Zi) / [Baidu Drive](https://pan.baidu.com/s/1Qu-0l9w0ja92nzrlWMRhoQ) (Password: 2t1l, Size: 5.45G).”

**Comment by GewelsJI** [comment]
Please download these segmentation results, and use this [toolbox](https://github.com/GewelsJI/VPS/tree/main/eval) to evaluate them.

**Comment by Zachary-Hwang** [comment]
I mean I had download the file named "Benchmark", how can  I use it?

**Comment by Zachary-Hwang** [comment]
I mean this "Or you can directly download the complete VPS benchmark including prediction map of each competitor at download link: [OneDrive](https://anu365-my.sharepoint.com/:u:/g/personal/u7248002_anu_edu_au/ESS2WHOQvLhMl5ci8wNO6yYBjnh6EVcp5vYO1z4JoOKUNg?e=nJe6Zi) / [Baidu Drive](https://pan.baidu.com/s/1Qu-0l9w0ja92nzrlWMRhoQ) (Password: 2t1l, Size: 5.45G).”" how can I get the prediction map of each competitor in the file named  "Benchmark".

**Comment by Zachary-Hwang** [comment]
Thank you！problem Sloved！
