### ISSUE TITLE
Is the time information of the video mentioned in the paper?

### ISSUE THREAD

**Issue by yike5022** [GewelsJI/VPS#22]

**Comment by GewelsJI** [comment]
Hello, what's your exact meaning of time information?

**Comment by yike5022** [comment]
Temporal feature，it is often mentioned along with spatial features

**Comment by GewelsJI** [comment]
Sure, you can refer to the original paper. Our NS block is used to model spatial-temporal relationships.

**Comment by yike5022** [comment]
thank you for your answer
