### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by xff12138** [GewelsJI/VPS#24]
编译时遇到这个错误该如何解决？

![67BDF32F1941A07991A192125ADF61BA](https://github.com/GewelsJI/VPS/assets/58496725/84c3ea83-eb74-41f4-b884-0d4ed18243ee)

**Comment by GewelsJI** [comment]
This error almost occurred when your CUDA version (NOTE: use your base CUDA not your torch CUDA) is not matching to your torch. Please follow and use the same version as mentioned in our GitHub.

**Comment by xff12138** [comment]
Thank you for your reply. I have solved the problem using base CUDA.

**Comment by GewelsJI** [comment]
That's good!
