### ISSUE TITLE
Visual Attributes

### ISSUE THREAD

**Issue by lxr-1204** [GewelsJI/VPS#25]
First of all, thank you for this meaningful job！
Secondly, for the Visual Attributes you proposed, if I want to get the Visual Attributes corresponding to each picture, could you tell me where I should look for it?
e.g. image_name_00001.jpg   -->  IB , HO
image_name_00002.jpg   -->  FM , SO
......
![3a8c04f37bd6dff9ffaa0c2bd3391dc](https://github.com/GewelsJI/VPS/assets/80816646/00ca1f84-21b1-4b8e-aec7-3be96dac1644)

**Comment by GewelsJI** [comment]
Hi, @lxr-1204 

Thanks for your attention.

We provide video-level attributes analysis at this stage, please refer to this link to download:

https://docs.google.com/spreadsheets/d/1J33EvrEcZp5CMWtKN_4VNdhp4EQsjMSf/edit?usp=sharing&ouid=117958307137184272405&rtpof=true&sd=true

Best
