### ISSUE TITLE
Regarding the role of the NS module in the model, why use two?

### ISSUE THREAD

**Issue by yike5022** [GewelsJI/VPS#27]
Hello, now I have something I don't understand about the NS module in the model, and I would like to ask you. If the role of the first NS module is to fuse local and global features, then what is the role of the second NS module, I look forward to receiving your reply.

**Comment by GewelsJI** [comment]
That's good question. As discussed in section 4.3.3, we use the first NS block for global spatial-temporal modelling, which means integrating global information into local temporal window. Also, as in section 4.3.4, we use the second NS block to learn better representations using both global and local features. Hope this insight helps you a lot.

Best,
Daniel.

**Comment by yike5022** [comment]
Thank you for your reply!
