### ISSUE TITLE
UNABLE TO DOWNLOAD DATASET

### ISSUE THREAD

**Issue by prabin333** [GewelsJI/VPS#30]
Hi, if i download dataset from the link drive,there are some files are missing  after the download..

**Comment by GewelsJI** [comment]
Hi @prabin333 

which link has expired?

**Comment by prabin333** [comment]
├──data
    ├──SUN-Positive
        ├──case1
            ├──image_name.jpg
            |...
        ├──case2
        |...
    ├──SUN-SEG-Annotation
        ├──TrainDataset
            ├──GT
                ├──case1_1
                    ├──image_name.png
                    |...
            ├──Edge
                |...
            ├──Scribble
                |...
            ├──Polygon
                |...
            ├──Classification
                ├──classification.txt
            ├──Detection
                ├──bbox_annotation.json
        ├──TestEasyDataset
            ├──Seen
                ├──GT
                |...
            ├──Unseen
                ├──GT
                |...
        ├──TestHardDataset
            ├──Seen
                ├──GT
                |...
            ├──Unseen
                ├──GT
                |...


SUN POSITIVE DIR IMAGES ARE TAKEN FROM WHICH DIR OF ORIGINAL DATASET??

**Comment by prabin333** [comment]
├──data
    ├──SUN-SEG
        ├──TrainDataset
            ├──Frame  # The images from SUN dataset
                ├──case1_1
                    ├──image_name_00001.jpg
                    |...
                ├──case1_3
                |...
            ├──GT  # Object-level segmentation mask
                ├──case1_1
                    ├──image_name_00001.png
                    |...
                ├──case1_3
                |...
            ├──Edge  # Weak label with edge
                |...
            ├──Scribble  # Weak label with scribble
                |...
            ├──Polygon  # Weak label with Polygon
                |...
            ├──Classification  # Category classification annotation
                ├──classification.txt
            ├──Detection  # Bounding box
                ├──bbox_annotation.json
        ├──TestEasyDataset
            ├──Seen
                ├──Frame
                    ├──case2_3
                    |...
                ├──GT
                    ├──case2_3
                    |...
                |...
            ├──Unseen
                ├──Frame
                    ├──case3_1
                    |...
                ├──GT
                    ├──case3_1
                    |...
                |...
        ├──TestHardDataset
            ├──Seen
                ├──Frame
                    ├──case1_2
                    |...
                ├──GT
                    ├──case1_2
                    |...
                |...
            ├──Unseen
                ├──Frame
                    ├──case10_1
                    |...
                ├──GT
                    ├──case10_1
                    |...
                |...


NOW MY DATASET IS IN THIS FORMAT...SAY FROM THIS WHAT IMAGES ARE TAKEN FOR DATA PREPARATION OF SUN POSITIVE?

**Comment by GewelsJI** [comment]
Have you download the dataset from SUN?

**Comment by prabin333** [comment]
NO i downloaded dataset from your drive link...

**Comment by GewelsJI** [comment]
Please download SUN first, and then use our script to process.

**Comment by lzl2040** [comment]
> Please download SUN first, and then use our script to process.

I sent him an email seven days ago, but there was no reply. Could you remind him? Thanks very much!
