### ISSUE TITLE
Quantitative comparison

### ISSUE THREAD

**Issue by Scatteredrain** [GewelsJI/VPS#31]
Hello author! I can't find the metrics results or prediction maps of the image-based models on SUN-SEG-Easy/Hard *Seen* datasets. Can you provide the prediction maps or the trained weights? Thanks!

**Comment by GewelsJI** [comment]
HI @Scatteredrain 

All amazing things are listed here: https://github.com/GewelsJI/VPS?tab=readme-ov-file#5-vps-benchmark

Thanks.

**Comment by Scatteredrain** [comment]
@GewelsJI Thanks for your quick reply! But in this link: https://pan.baidu.com/s/1Qu-0l9w0ja92nzrlWMRhoQ  
I can't find the prediction maps on the two Seen datasets of some models (only Unseen), like UNet and other image-based methods. 
I wonder if you uploaded these results.

**Comment by GewelsJI** [comment]
We actually release all the pred results in the download link, and everything is available for the community. Could you please show me the file extracted from this tar file?

Best

**Comment by Scatteredrain** [comment]
![image](https://github.com/GewelsJI/VPS/assets/105765793/ac27154c-25ec-4233-b3d0-df69437a1ccc)
I think you may not give the results because the Image-based approach experiments on *Seen* datasets are not shown in your paper(PNS+)

**Comment by GewelsJI** [comment]
Sorry, I just mis-understood your question. We did not evaluate the performance of image-based methods on seen datasets as we are interested in the spatial-temporal association abilities during this stage. You can term seen datasets as a validation set, so we disregard them. More details can be found in our paper: 
<img width="1079" alt="image" src="https://github.com/GewelsJI/VPS/assets/38354957/35649f7a-8b6c-4ba6-9696-bf947707f25e">

Hope you best!

**Comment by GewelsJI** [comment]
And as for the trained weights, I think it is not hard to implement (I mean UNet-family models) and to retrain them, you can try it then. Happy to see some interesting results from your side. 

Hope our work helps you a lot. Thanks

**Comment by Scatteredrain** [comment]
Thanks for the answer, that's exactly what I want to know!
