### ISSUE TITLE
How to get fps and real-time video view?

### ISSUE THREAD

**Issue by yeonhyochoi** [GewelsJI/VPS#34]
Hi, thanks to your nice work.

I am leaving a message because I have a question.
First, I want to find the fps. Second, I have an actual endoscopy video, and I want to make it into a video that shows the location of the lesion in real time, like your video. Is there any related code?

**Comment by GewelsJI** [comment]
Assume it is not hard to implement such simple function, whatever by yourself or assisting with Codellama. You can just use our model to generate some prediction masks and generate the real-time video what you want.

Hope everything best for you.

Thanks,
Daniel
