### ISSUE TITLE
Hello, may I ask what about the quantitative evaluation results of other projects under ./eval/eval-result? Can it be borrowed directly?Looking forward to your reply!

### ISSUE THREAD

**Issue by yike5022** [GewelsJI/VPS#38]

**Comment by GewelsJI** [comment]
Could you please make it more clearly?

**Comment by yike5022** [comment]
I would like to know if these quantitative results are reliable

**Comment by GewelsJI** [comment]
Surly, you can feel free to use them. But to ensure reliable output, you can evaluate it again in your platform.

**Comment by yike5022** [comment]
ok.thank you !
