### ISSUE TITLE
Questions about downloading data from the SUN Colonoscopy Video Database

### ISSUE THREAD

**Issue by jue12345** [GewelsJI/VPS#4]
Thanks for reading this question!
The email address provided at the end of the data download page of the SUN Colonoscopy Video Database is **hitoh (a t) mori.m.is.nagoya-u.ac.jp**,
This is an unfeasible email address, may I directly change the email address to **hitoh@mori.m.is.nagoya-u.ac.jp** and then send the request email?
thank you!

**Comment by GewelsJI** [comment]
Yes. You are right

**Comment by Selinia** [comment]
> 感谢您阅读这个问题！ SUN结肠镜视频数据库数据下载页面末尾提供的邮箱地址是**hitoh（t）mori.m.is.nagoya-u.ac.jp**，这是一个不可行的电子邮件地址，我可以直接将电子邮件地址更改为 **[hitoh@mori.m.is.nagoya-u.ac.jp](mailto:hitoh@mori.m.is.nagoya-u.ac.jp)** 然后发送请求邮件吗？ 谢谢！

Hello, I wonder if you have received a reply? I write to [hitoh@mori.m.is.nagoya-u.ac.jp](mailto:hitoh@mori.m.is.nagoya-u.ac.jp) for dataset application but was informed that my message could not be delivered.

**Comment by GewelsJI** [comment]
Hi, @Selinia 

I discussed with original authors via hitoh@mori.m.is.nagoya-u.ac.jp. I am not sure why you can not use this address. Or you can search their recent research papers and find the new valid address available.

Best
