### ISSUE TITLE
Definitions of the visual attributes

### ISSUE THREAD

**Issue by lofrienger** [GewelsJI/VPS#43]
Hi, from the paper I could only find the descriptions of the 10 general attributes in the [Google sheet](https://docs.google.com/spreadsheets/d/1J33EvrEcZp5CMWtKN_4VNdhp4EQsjMSf/edit?usp=sharing&ouid=117958307137184272405&rtpof=true&sd=true).
Could you please share the descriptions of other categories (Shape, Location, Pathological diagnosis) of attributes?

Thanks a lot!!

**Comment by GewelsJI** [comment]
Hi @lofrienger 

I am not quite getting your question here. Could you concrete it?

Best,
Gepeng.

**Comment by GewelsJI** [comment]
Hi,

Please refer to [here](https://github.com/GewelsJI/VPS/blob/main/docs/DATA_DESCRIPTION.md#label-vi-attributes-description) for more details.

Best
