### ISSUE TITLE
Hi, QR code not available, please update.

### ISSUE THREAD

**Issue by szuzzb** [GewelsJI/VPS#6]
Hi, QR code not available, please update.

**Comment by GewelsJI** [comment]
Hi, the new QR code is here

https://github.com/GewelsJI/VPS/blob/main/assets/wechat_group_qr_code.jpg

Welcome to our chat group.

**Comment by szuzzb** [comment]
Thanks

**Comment by Moqixis** [comment]
请问可以再更新一下二维码嘛？感谢。

**Comment by GewelsJI** [comment]
Hi, @Moqixis

QR code has been updated in this [page](https://github.com/GewelsJI/VPS/blob/main/assets/wechat_group_qr_code.jpg).

**Comment by Moqixis** [comment]
> Hi, @Moqixis
> 
> QR code has been updated in this [page](https://github.com/GewelsJI/VPS/blob/main/assets/wechat_group_qr_code.jpg).

Thank you very much！！
